refactoring
Murkiness/ueberauth_crowd pull request #2
Opened 2020-10-26 14:55 UTC by Murkiness

2020-10-27 14:14 UTC, mugimaru73 requested changes

2020-10-27 14:14 UTC, mugimaru73 commented on lib/ueberauth/strategy/crowd.ex
> +    return_to = cb_url <> get_additional_params_string(conn.params)
Кажется, что можно сделать просто 
```
Map.take(params, ["list", "of", "params"]) |> URI.encode_query()
```

Стоит еще учитывать, что я могу захотеть настроить callback_url с query params в нем (например, `http://myhost/callback?foo=1`). 
В текущей реализации получится `?foo=1?something=else`.
Предлагаю работать с урлами параметрами через `URI.encode_query/1`,  `URI.decode_query/1`, работать с параметрами как с мапом и собирать результат внутри %URI{}. Кажется, что за счет этого можно не решать руками кучу сопутствующих проблем.

2020-10-28 11:51 UTC, Murkiness commented on lib/ueberauth/strategy/crowd.ex
> +    return_to = cb_url <> get_additional_params_string(conn.params)
@mugimaru73 исправил (вроде)

2020-10-28 11:53 UTC, mugimaru73 commented on lib/ueberauth/strategy/crowd.ex
> +    return_to = cb_url <> get_additional_params_string(conn.params)
Ага, осталось добиться зеленого билда :)

2020-10-28 11:53 UTC, mugimaru73 approved these changes

2020-10-28 11:55 UTC, mugimaru73 commented on lib/ueberauth/strategy/crowd.ex
> +    return_to = cb_url <> get_additional_params_string(conn.params)
Да, осталось исправить CI билд

2020-10-28 12:49 UTC, merged